services:
  postgres:
    container_name: test-postgres
    image: ankane/pgvector:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdf_chat_user -d pdf_chat_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=5uperSecr3tP@ssw0rd!
      - POSTGRES_USER=pdf_chat_user
      - POSTGRES_DB=pdf_chat_test

  test:
    container_name: test
    build: ./backend/test
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ./backend/test/files:/app/files


networks:
  test-network:
    driver: bridge

volumes:
  postgres-data: