services:
  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - 8000:8000
    env_file:
      - .env
  postgres:
    image: ankane/pgvector:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pdf_chat_user -d pdf_chat"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
    ports:
      - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=5uperSecr3tP@ssw0rd!
      - POSTGRES_USER=pdf_chat_user
      - POSTGRES_DB=pdf_chat

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data: